<?php

require_once('../php/DBConn_Dave.php');
include_once("../users_functions.php");
include_once("../address_functions.php");

session_start();

//SETUP SESSION VARIABLES:
$_SESSION['USER']['USER_ID'] = $_POST['USER_ID'];
$_SESSION['USER']['FIRST_NAME'] = $_POST['FIRST_NAME'];
$_SESSION['USER']['LAST_NAME'] = $_POST['LAST_NAME'];
$_SESSION['USER']['NATIONAL_ID'] = $_POST['NATIONAL_ID'];
$_SESSION['USER']['EMAIL'] = $_POST['EMAIL'];
$_SESSION['USER']['PHONE'] = $_POST['PHONE'];
$_SESSION['USER']['STREET_NO'] = $_POST['STREET_NO'];
$_SESSION['USER']['STREET'] = $_POST['STREET'];
$_SESSION['USER']['OFFICE'] = $_POST['OFFICE'];
$_SESSION['USER']['BUILDING_NUMBER'] = $_POST['BUILDING_NUMBER'];
$_SESSION['USER']['DATE_OF_BIRTH'] = $_POST['DATE_OF_BIRTH'];
$_SESSION['USER']['BLOOD_TYPE'] = $_POST['BLOOD_TYPE'];
$_SESSION['USER']['GENDER'] = $_POST['GENDER'];
$_SESSION['USER']['LANGUAGE_PREF'] = $_POST['LANGUAGE_PREF'];
$_SESSION['USER']['PASSPORT_NO'] = $_POST['PASSPORT_NO'];
$_SESSION['USER']['AREA'] = $_POST['AREA'];
$_SESSION['USER']['AREA_CODE'] = $_POST['AREA_CODE'];
$_SESSION['USER']['CITY'] = $_POST['CITY'];
$_SESSION['USER']['PASSWORD'] = $_POST['PASSWORD'];
$_SESSION['USER']['TITLE'] = $_POST['TITLE'];

echo $_SESSION['FIRST_NAME'];
echo $_SESSION['LAST_NAME'];
echo $_SESSION['EMAIL'];

?>